name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Update this to match your project's Java version
        distribution: 'temurin' # Specify the Java distribution (e.g., temurin, zulu, adopt)

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Build project
      run: mvn package -DskipTests

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar
